name: Node CI

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Dependencies Install
      run: npm ci
      env:
        CI: true

    - name: Build and Test
      run: npm run build
      env:
        CI: true
